version: '3'
services:
  bookstack:
    image: linuxserver/bookstack:latest
    container_name: my-bookstack
    restart: always   #if the container fails, policy is to do a restart automatically always 
    ports:
      - "8080:80" # TO DO: change these to more secure ports
    volumes:
      - /Users/shruthinaidu/gitrepos/bookstack-on-kubenetes/data:/config
    environment:
      - PUID = 1000
      - PGID = 1000
      - APP_URL = http://localhost:8080
      - DB_HOST = db
      - DB_DATABASE = bookstack
      - DB_USERNAME = ${{secrets.BOOKSTACK_DB_USERNAME}}
      - DB_PASSWORD = ${{secrets.BOOKSTACK_DB_PASSWORD}}
    depends_on:
      - db
  db:
    image: mariadb
    container_name: bookstack-mariadb
    restart: always
    environment:
      - MYSQL_DB = bookstack
      - MYSQL_USER = ${{secrets.BOOKSTACK_DB_USERNAME}}
      - MYSQL_PASSWORD = ${{secrets.BOOKSTACK_DB_PASSWORD}}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./db:/var/lib/mysql